flags:
  synquid:
    synquid: true
packages:
  - '.'
resolver: lts-15.3
extra-include-dirs:
  - /home/carrotvm/local/z3-master/src/api
extra-lib-dirs:
  - /home/carrotvm/local/z3-master/build  
extra-deps:
  - z3-408.2
